tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "php", restart_service: true
brew "composer"
brew "dnsmasq"
brew "gnupg"
brew "httpd"
brew "ios-webkit-debug-proxy"
brew "mailhog", restart_service: true
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "starship"
brew "tree"
brew "wp-cli"
brew "yadm"
brew "yarn"
brew "zoxide"
cask "android-studio"
cask "authy"
cask "bitwarden"
cask "docker"
cask "fig"
cask "figma"
cask "flutter"
cask "font-fira-code"
cask "google-chrome"
cask "insomnia"
cask "notion"
cask "spotify"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "webcatalog"
cask "whatsapp"
cask "zoom"
